export default {
  ADD_NAME_EMAIL: 'ADD_NAME_EMAIL',
  ADD_LOCATION_DATA: 'ADD_LOCATION_DATA',
  ADD_SOCIAL_NETWORKS: 'SOCIAL_NETWORKS',
  ADD_CAT_IMAGE: 'ADD_CAT_IMAGE',
  GO_OVER_AGAIN: 'GO_OVER_AGAIN',
  IS_VALIDATED_FORM: 'IS_VALIDATED_FORM'
};
